//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsGroup
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string imageUri { get; set; }
        public short Age { get; set; }
        public int RolesId { get; set; }
        public int GroupsId { get; set; }
    
        public virtual Roles Role { get; set; }
        public virtual Groups Group { get; set; }
    }
}
